name: Release Plugin
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
permissions:
  contents: read # for checkout
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: |
          npm ci
      - name: Release
        run: |
          npm run release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
